import { Discipline } from "./types";

export const INITIAL_DISCIPLINES_DATA: Discipline[] = [
  // --- 1º SEMESTRE ---
  {
    id: "16001PP",
    periodo: 1,
    nome: "Fotografia e Tratamento de Imagem",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 80,
    chTeo: 20,
    chPra: 60,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 13,
    credito: 4,
    ementa: "A fotografia digital e seus elementos. A composição, os ângulos, os planos, esquemas de iluminação utilizados nas diversas áreas da fotografia publicitária. Produção de material fotográfico publicitário em estúdio e em locações. Tratamento de imagens em softwares específicos. Técnicas para edição digital de imagens. Montagem de catálogo publicitário fotográfico.",
    praticaAtividade: "Produção fotográfica e tratamento digital de imagens em estúdio e computador",
    ambientePratica: "Estúdio de Fotografia / Lab. de Informática",
    nivelExigencia: "Exigência Média"
  },
  {
    id: "16002PP",
    periodo: 1,
    nome: "Introdução à Publicidade",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 40,
    chTeo: 40,
    chPra: 0,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 7,
    credito: 2,
    ementa: "Conceituação de Publicidade e Propaganda. Origem e mecanismos da publicidade. O desenvolvimento da Publicidade e Propaganda no Brasil e no mundo. A Publicidade e Propaganda na cultura contemporânea. A Publicidade e Propaganda na contexto mercadológico. Os mitos da Publicidade e Propaganda. As implicações éticas da publicidade junto aos públicos-alvo. O organograma de agências. A prática publicitária: anúncios e campanhas. A propaganda política: formatos, responsabilidade e ética profissional.",
    praticaAtividade: "Estudos de caso, seminários e análise crítica de campanhas históricas",
    ambientePratica: "Sala de Aula",
    nivelExigencia: "Exigência Alta"
  },
  {
    id: "16004PP",
    periodo: 1,
    nome: "Processos Criativos",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 40,
    chTeo: 40,
    chPra: 0,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 7,
    credito: 2,
    ementa: "Conceitos de criatividade a partir dos diferentes referenciais teóricos. O diálogo entre criatividade e inovação. O desenvolvimento da criatividade em diferentes linguagens e suportes. Aplicação de técnicas e ferramentas associadas ao processo criativo, de uso individual e/ou em grupo.",
    praticaAtividade: "Sessões de brainstorm, dinâmicas de desbloqueio criativo e mapas mentais",
    ambientePratica: "Sala de Aula / Lab. de Informática",
    nivelExigencia: "Exigência Média"
  },
  {
    id: "16090PP",
    periodo: 1,
    nome: "Produção Artística (módulo integrador)",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 80,
    chTeo: 20,
    chPra: 60,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 13,
    credito: 4,
    ementa: "Pesquisa, planejamento e desenvolvimento de projeto ARTÍSTICO relacionado à criação, produção artística ou cultural com aproximações entre comunicação, arte e cultura, envolvendo (ou não) instituições públicas ou privadas.",
    praticaAtividade: "Planejamento e execução de projeto de intervenção estética ou mostra cultural",
    ambientePratica: "Agência Experimental / Ateliê de Artes",
    nivelExigencia: "Exigência Baixa"
  },
  {
    id: "16047PP",
    periodo: 1,
    nome: "História e Teorias da Comunicação",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 80,
    chTeo: 80,
    chPra: 0,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 13,
    credito: 4,
    ementa: "O advento da comunicação de massa e a indústria cultural. Conceitos de comunicação, história e teoria. Surgimento da imprensa e seu desenvolvimento na era moderna e contemporânea. Evolução histórica do pensamento sobre os fenômenos da comunicação: teorias funcionalistas; estudos culturais; teoria crítica; semiótica; o pensamento latino-americano; panoramas contemporâneos sobre o funcionamento das mídias.",
    praticaAtividade: "Fichamento de textos clássicos e elaboração de ensaios analíticos de mídia",
    ambientePratica: "Sala de Aula / Biblioteca",
    nivelExigencia: "Exigência Alta"
  },

  // --- 2º SEMESTRE ---
  {
    id: "PX001PUB",
    periodo: 2,
    nome: "Programa de Extensão - PROEX I",
    areaConhecimento: "PROJETO EXTENSÃO",
    tipo: "PRESENCIAL",
    ch: 80,
    chTeo: 0,
    chPra: 0,
    chEst: 0,
    chEad: 0,
    chExt: 80,
    chAds: 0,
    credito: 4,
    ementa: "Experimentação de ações que inter-relacionam teoria e prática, tendo como alvo o atendimento das demandas sociais comunitárias de Curitiba e região.",
    praticaAtividade: "Atividades e projetos comunitários de extensão e diagnósticos locais",
    ambientePratica: "Comunidade / Campo",
    nivelExigencia: "Exigência Baixa"
  },
  {
    id: "16007PP",
    periodo: 2,
    nome: "Fotografia Publicitária",
    areaConhecimento: "OBRIGATÓRIA",
    tipo: "PRESENCIAL",
    ch: 80,
    chTeo: 20,
    chPra: 60,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 13,
    credito: 4,
    ementa: "A fotografia publicitária e seus elementos. A composição, os ângulos, os planos, as iluminações utilizadas nas diversas áreas da fotografia publicitária. Produção de material fotográfico publicitário em estúdio e em locações. Montagem de catálogo publicitário com fotos.",
    praticaAtividade: "Ensaios fotográficos de produtos (still) e modelos com iluminação de estúdio",
    ambientePratica: "Estúdio de Fotografia",
    nivelExigencia: "Exigência Média"
  },
  {
    id: "16091PP",
    periodo: 2,
    nome: "Sociedade e Criatividade",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 40,
    chTeo: 10,
    chPra: 30,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 7,
    credito: 2,
    ementa: "Pesquisa, planejamento e desenvolvimento de projeto SOCIAL relacionado à criação, produção artística ou cultural com aproximações entre comunicação, arte e cultura, envolvendo (ou não) instituições públicas ou privadas.",
    praticaAtividade: "Projeto social integrador com propostas de soluções criativas comunitárias",
    ambientePratica: "Sala de Aula / Comunidade",
    nivelExigencia: "Exigência Baixa"
  },
  {
    id: "16079PP",
    periodo: 2,
    nome: "Escrita Criativa",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 80,
    chTeo: 20,
    chPra: 60,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 13,
    credito: 4,
    ementa: "Vida social e linguagem. A comunicação como interação simbólica. Conceitos de Signo, Texto, Narrativa, Estilo e Discurso. As relações interdisciplinares para a interpretação linguística de um texto. Os diferentes tipos de textos relacionados à Comunicação Social.",
    praticaAtividade: "Oficinas de redação criativa, storytelling, crônicas e microcontos",
    ambientePratica: "Sala de Aula / Lab. de Informática",
    nivelExigencia: "Exigência Média"
  },
  {
    id: "16005PP",
    periodo: 2,
    nome: "Editoração Publicitária",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 80,
    chTeo: 10,
    chPra: 70,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 13,
    credito: 4,
    ementa: "Métodos e técnicas de diagramação, vetorização, manipulação de imagem e de editoração eletrônica aplicados à publicidade. Softwares para vetorização e tratamento de imagens. Conceitos gerais sobre criação e utilização de imagens gráficas.",
    praticaAtividade: "Vetorização e diagramação de peças gráficas, catálogos e folhetos",
    ambientePratica: "Laboratório de Informática",
    nivelExigencia: "Exigência Alta"
  },
  {
    id: "NCH001",
    periodo: 2,
    nome: "Arte e Cultura no Mundo Contemporâneo",
    areaConhecimento: "OBRIGATÓRIA - NÚCLEO COMUM",
    tipo: "PRESENCIAL",
    ch: 40,
    chTeo: 40,
    chPra: 0,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 7,
    credito: 2,
    ementa: "Introdução aos principais movimentos artísticos mundiais – da pré-história ao pós-modernismo. Elementos e conceitos básicos para a compreensão do fenômeno artístico no contexto cultural dos diferentes períodos históricos. Aspectos formais de análise das artes visuais – recursos de composição e de construção da imagem. Comunicação de massa e artes – apropriações e referências.",
    praticaAtividade: "Análise iconográfica de anúncios e debates dirigidos sobre arte pós-moderna",
    ambientePratica: "Sala de Aula",
    nivelExigencia: "Exigência Baixa"
  },

  // --- 3º SEMESTRE ---
  {
    id: "16009PP",
    periodo: 3,
    nome: "Direção de Arte",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 80,
    chTeo: 20,
    chPra: 60,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 13,
    credito: 4,
    ementa: "Técnicas de comunicação visual aplicadas à propaganda: tipografia, luz, cor, fotografia, composição, identidade visual e linguagem. Criação publicitária. Planejamento visual, criação e produção de conceitos e imagens para anúncios e peças de comunicação para mídias impressas, exteriores, eletrônicas e digitais.",
    praticaAtividade: "Desenvolvimento de guia de identidade visual e layouts publicitários digitais",
    ambientePratica: "Laboratório de Informática / Agência Experimental",
    nivelExigencia: "Exigência Média"
  },
  {
    id: "16010PP",
    periodo: 3,
    nome: "Mídia",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 40,
    chTeo: 40,
    chPra: 0,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 7,
    credito: 2,
    ementa: "Fundamentos conceituais de mídia. Estrutura do departamento de mídia. O profissional de mídia. A articulação estratégica e tática dos diferentes meios no planejamento de mídia. Dados de mídia e sua aplicação no planejamento: audiência, GRP, CPM, métricas de controle e avaliação de resultados, cobertura, penetração, perfil do público-alvo. Leitura e interpretação de pesquisas de consumo de mídia. Alocação de verbas no planejamento de mídia. Criatividade em planejamento de mídia. A compra de Mídia nos diversos meios - práticas do mercado nacional.",
    praticaAtividade: "Simulação de compra e planejamento estratégico de mídia com dados de audiência",
    ambientePratica: "Sala de Aula / Lab. de Informática",
    nivelExigencia: "Exigência Alta"
  },
  {
    id: "16012PP",
    periodo: 3,
    nome: "Produção Gráfica",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 40,
    chTeo: 20,
    chPra: 20,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 7,
    credito: 2,
    ementa: "A tecnologia gráfica: visão histórica no contexto da Publicidade. Sistemas e processos de produção, materiais: teoria e prática. O trabalho das gráficas e as principais tecnologias utilizadas. Pré-produção, produção e pós-produção.",
    praticaAtividade: "Acompanhamento prático de fechamento de arquivo, facas de corte e acabamentos",
    ambientePratica: "Laboratório de Informática / Gráfica Parceira",
    nivelExigencia: "Exigência Baixa"
  },
  {
    id: "16013PP",
    periodo: 3,
    nome: "Redação Publicitária",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 80,
    chTeo: 80,
    chPra: 0,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 13,
    credito: 4,
    ementa: "Pensamento criativo e discurso publicitário. Relações entre os códigos verbal e não-verbal na publicidade. A morfologia do anúncio impresso. Recursos de linguagem aplicados à publicidade. A criação do título, do slogan e do texto publicitário. Criação da mensagem publicitária para diferentes objetivos comerciais. Adequação da mensagem para diferentes meios de comunicação. Redação publicitária online e off-line.",
    praticaAtividade: "Redação de copys, roteiros de rádio e TV, slogans e peças conceituais",
    ambientePratica: "Sala de Aula",
    nivelExigencia: "Exigência Alta"
  },
  {
    id: "16092PP",
    periodo: 3,
    nome: "Agência Experimental (módulo integrador)",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 80,
    chTeo: 10,
    chPra: 70,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 13,
    credito: 4,
    ementa: "Pesquisa, planejamento e desenvolvimento de projeto AGÊNCIA EXPERIMENTAL relacionado à criação, produção artística ou cultural com aproximações entre comunicação, arte e cultura, envolvendo (ou não) instituições públicas ou privadas.",
    praticaAtividade: "Atendimento de clientes reais da comunidade em agência experimental simulada",
    ambientePratica: "Agência Experimental (LabCom)",
    nivelExigencia: "Exigência Média"
  },

  // --- 4º SEMESTRE ---
  {
    id: "PX002PUB",
    periodo: 4,
    nome: "Programa de Extensão - PROEX II",
    areaConhecimento: "PROJETO EXTENSÃO",
    tipo: "PRESENCIAL",
    ch: 80,
    chTeo: 0,
    chPra: 0,
    chEst: 0,
    chEad: 0,
    chExt: 80,
    chAds: 0,
    credito: 4,
    ementa: "Experimentação de ações de extensão curricularizada obrigatória que inter-relacionam teoria e prática publicitária sob a perspectiva de responsabilidade socioambiental e ESG.",
    praticaAtividade: "Execução de campanhas e ações com temática socioambiental",
    ambientePratica: "Comunidade / Campo",
    nivelExigencia: "Exigência Baixa"
  },
  {
    id: "16093PP",
    periodo: 4,
    nome: "Novas Soluções Audiovisuais",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 80,
    chTeo: 40,
    chPra: 40,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 13,
    credito: 4,
    ementa: "Pesquisa, planejamento e desenvolvimento de projeto AUDIOVISUAL relacionado à criação, produção de novas mídias e roteirização aplicada com inovações tecnológicas e novos canais de mídia.",
    praticaAtividade: "Gravação e edição de peças em vídeo destinadas a redes sociais e streaming",
    ambientePratica: "Estúdio de TV e Vídeo",
    nivelExigencia: "Exigência Média"
  },
  {
    id: "16015PP",
    periodo: 4,
    nome: "Produção Audiovisual",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 80,
    chTeo: 20,
    chPra: 60,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 13,
    credito: 4,
    ementa: "Características da televisão e do cinema como mídia publicitária e como formato de linguagem; Gêneros televisivos em publicidade; Processo de produção em tv e cinema; redação para roteiros; produção e edição de filmes publicitários.",
    praticaAtividade: "Operação de câmera, gravação externa, direção de cena e montagem",
    ambientePratica: "Estúdio de TV e Vídeo / Ilhas de Edição",
    nivelExigencia: "Exigência Média"
  },
  {
    id: "16016PP",
    periodo: 4,
    nome: "Produção de Som",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 80,
    chTeo: 20,
    chPra: 60,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 13,
    credito: 4,
    ementa: "Introdução à física do som. A audição humana. As dimensões da linguagem sonora: como as manifestações do som, enquanto evento físico, constituem linguagens. Processos e sistemas de captação e gravação de áudio; Tipos de microfones e suas aplicações. Introdução à captação de som direto. Usos narrativos do som direto. Desenho de som.",
    praticaAtividade: "Captação de voz, mixagem de jingles, sonoplastia e produção de spots de rádio",
    ambientePratica: "Estúdio de Áudio e Rádio",
    nivelExigencia: "Exigência Média"
  },
  {
    id: "INST5",
    periodo: 4,
    nome: "Comportamento Empreendedor",
    areaConhecimento: "INSTITUCIONAL",
    tipo: "A DISTÂNCIA",
    ch: 40,
    chTeo: 0,
    chPra: 0,
    chEst: 0,
    chEad: 40,
    chExt: 0,
    chAds: 0,
    credito: 2,
    ementa: "Noções de empreendedorismo. O perfil dos profissionais empreendedores nas organizações. Mudança nas relações de trabalho. Tomada de decisão e riscos. O marketing como ferramenta para o empreendedor. Elaboração de planos de negócios aplicados à publicidade.",
    praticaAtividade: "Construção de Canvas de Modelo de Negócio para startups de publicidade",
    ambientePratica: "Ambiente Virtual de Aprendizagem (AVA)",
    nivelExigencia: "Exigência Baixa"
  },
  {
    id: "16094PP",
    periodo: 4,
    nome: "Publicidade na Comunidade",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 80,
    chTeo: 40,
    chPra: 40,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 13,
    credito: 4,
    ementa: "Desenvolvimento de projetos comunitários simulando campanhas e diagnósticos publicitários voltados para o terceiro setor, ONGs locais de Curitiba e promoção do bem-estar social.",
    praticaAtividade: "Pesquisa e formulação de campanhas de conscientização social",
    ambientePratica: "Comunidade / Agência Experimental",
    nivelExigencia: "Exigência Baixa"
  },

  // --- 5º SEMESTRE ---
  {
    id: "INST013",
    periodo: 5,
    nome: "Formação Sociocultural e Ética",
    areaConhecimento: "INSTITUCIONAL",
    tipo: "A DISTÂNCIA",
    ch: 40,
    chTeo: 0,
    chPra: 0,
    chEst: 0,
    chEad: 40,
    chExt: 0,
    chAds: 0,
    credito: 2,
    ementa: "Ética e política - principais correntes contemporâneas. Democracia, liberdade, justiça e responsabilidade social. Direitos humanos, relações étnico-raciais e cultura afro-brasileira, africana e indígena.",
    praticaAtividade: "Fóruns de debate orientados sobre dilemas éticos na sociedade moderna",
    ambientePratica: "Ambiente Virtual de Aprendizagem (AVA)",
    nivelExigencia: "Exigência Baixa"
  },
  {
    id: "16019PP",
    periodo: 5,
    nome: "Pesquisa e Comportamento do Consumidor",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 80,
    chTeo: 80,
    chPra: 0,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 13,
    credito: 4,
    ementa: "Comportamento de consumo. Pesquisa de mercado e suas técnicas no âmbito mercadológico e de comunicação. Desenvolvimento de planos de pesquisa e estudos qualitativos e quantitativos. Metodologias e relatórios de mercado.",
    praticaAtividade: "Formulação de questionários de mercado e modelagem de mapas de empatia",
    ambientePratica: "Sala de Aula / Campo",
    nivelExigencia: "Exigência Alta"
  },
  {
    id: "16095PP",
    periodo: 5,
    nome: "Planejamento de Comunicação",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 80,
    chTeo: 40,
    chPra: 40,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 13,
    credito: 4,
    ementa: "Pesquisa, planejamento e desenvolvimento de PLANO DE COMUNICAÇÃO completo para uma marca, produto ou serviço, integrando canais online e offline.",
    praticaAtividade: "Elaboração de briefing e planejamento tático/estratégico de canais",
    ambientePratica: "Sala de Aula / Agência Experimental",
    nivelExigencia: "Exigência Alta"
  },
  {
    id: "16087PP",
    periodo: 5,
    nome: "Narrativas Audiovisuais",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 40,
    chTeo: 10,
    chPra: 30,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 7,
    credito: 2,
    ementa: "Roteiro e narrativa audiovisual avançada. Estrutura dramática de comerciais de curta duração, storyboards, e edição narrativa de campanhas em vídeo.",
    praticaAtividade: "Roteirização avançada, diagramação de storyboards e layouts de cena",
    ambientePratica: "Sala de Aula / Estúdio de TV",
    nivelExigencia: "Exigência Média"
  },
  {
    id: "16088PP",
    periodo: 5,
    nome: "Narrativas em Áudio",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 40,
    chTeo: 10,
    chPra: 30,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 7,
    credito: 2,
    ementa: "Linguagem radiofônica, podcasts e sound branding. Produção de spots, jingles e estruturas de áudio interativas para marcas.",
    praticaAtividade: "Produção de podcasts, soundscapes de marca e edição multipista",
    ambientePratica: "Estúdio de Áudio / Ilhas de Edição",
    nivelExigencia: "Exigência Média"
  },
  {
    id: "16096PP",
    periodo: 5,
    nome: "Campanha Publicitária de Varejo",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 80,
    chTeo: 70,
    chPra: 10,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 13,
    credito: 4,
    ementa: "Desenvolvimento prático de CAMPANHA PUBLICITÁRIA DE VAREJO focada no mercado de Curitiba, com técnicas de trade marketing, material de PDV e ativação de vendas.",
    praticaAtividade: "Desenho de cartazes promocionais, folders e planejamento de ponto de venda",
    ambientePratica: "Laboratório de Informática / Sala de Aula",
    nivelExigencia: "Exigência Média"
  },
  {
    id: "INST012",
    periodo: 5,
    nome: "Meio Ambiente e Sustentabilidade",
    areaConhecimento: "OBRIGATÓRIA - NÚCLEO COMUM",
    tipo: "A DISTÂNCIA",
    ch: 40,
    chTeo: 0,
    chPra: 0,
    chEst: 0,
    chEad: 40,
    chExt: 0,
    chAds: 0,
    credito: 2,
    ementa: "Fundamentos teóricos e práticos de sustentabilidade e responsabilidade socioambiental corporativa. Sistemas de gestão ambiental (SGA) e aplicação de diretrizes ecológicas na comunicação de marcas.",
    praticaAtividade: "Estudo e redação de relatório corporativo focado em boas práticas ESG",
    ambientePratica: "Ambiente Virtual de Aprendizagem (AVA)",
    nivelExigencia: "Exigência Baixa"
  },

  // --- 6º SEMESTRE ---
  {
    id: "PX003PUB",
    periodo: 6,
    nome: "Programa de Extensão - PROEX III",
    areaConhecimento: "PROJETO EXTENSÃO",
    tipo: "PRESENCIAL",
    ch: 80,
    chTeo: 0,
    chPra: 0,
    chEst: 0,
    chEad: 0,
    chExt: 80,
    chAds: 0,
    credito: 4,
    ementa: "Experimentação e inserção em projetos práticos de extensão comunitária e cultural para aproximação com os problemas reais de comunicação do entorno da UniBrasil.",
    praticaAtividade: "Execução prática avançada de projeto extensionista em comunidade",
    ambientePratica: "Comunidade / Campo",
    nivelExigencia: "Exigência Baixa"
  },
  {
    id: "16089PP",
    periodo: 6,
    nome: "Live Marketing e Branded Experience",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 80,
    chTeo: 80,
    chPra: 0,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 13,
    credito: 4,
    ementa: "Ações promocionais, ativações de marcas, trade marketing e marketing de experiência. Eventos corporativos, promoções interativas e criação de vínculos emocionais com o consumidor em pontos físicos e digitais.",
    praticaAtividade: "Planejamento e simulação técnica de ativação promocional de rua",
    ambientePratica: "Sala de Aula",
    nivelExigencia: "Exigência Alta"
  },
  {
    id: "16022PP",
    periodo: 6,
    nome: "Ciberpublicidade",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 80,
    chTeo: 80,
    chPra: 0,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 13,
    credito: 4,
    ementa: "Inovações tecnológicas na comunicação. Convergência e conectividade digital. Comunicação mediada por computador (CMC), SEO/SEM, tráfego pago, mídias digitais e hibridismo cultural.",
    praticaAtividade: "Mapeamento de jornada de compra digital, SEO técnico e dashboards digitais",
    ambientePratica: "Sala de Aula / Laboratório de Informática",
    nivelExigencia: "Exigência Alta"
  },
  {
    id: "16042PP",
    periodo: 6,
    nome: "Tendências em Publicidade",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 40,
    chTeo: 40,
    chPra: 0,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 7,
    credito: 2,
    ementa: "Prospecção e estudo crítico de novas realidades tecnológicas e sociais aplicadas ao consumo e à comunicação, como inteligência artificial, influenciadores virtuais e novas dinâmicas algorítmicas.",
    praticaAtividade: "Estudos de coolhunting e pesquisas de prospecção sociocultural",
    ambientePratica: "Sala de Aula",
    nivelExigencia: "Exigência Média"
  },
  {
    id: "205ADM",
    periodo: 6,
    nome: "Business Intelligence",
    areaConhecimento: "OBRIGATÓRIA - NÚCLEO COMUM",
    tipo: "PRESENCIAL",
    ch: 40,
    chTeo: 40,
    chPra: 0,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 7,
    credito: 2,
    ementa: "Coleta, estruturação e análise de dados para tomada de decisões estratégicas de publicidade. Google Analytics, análise preditiva, métricas de redes sociais e BI voltado a campanhas de marketing.",
    praticaAtividade: "Elaboração de painéis analíticos com dados reais de marketing online",
    ambientePratica: "Laboratório de Informática",
    nivelExigencia: "Exigência Alta"
  },
  {
    id: "16040PP",
    periodo: 6,
    nome: "Optativa",
    areaConhecimento: "INSTITUCIONAL",
    tipo: "A DISTÂNCIA",
    ch: 80,
    chTeo: 0,
    chPra: 0,
    chEst: 0,
    chEad: 80,
    chExt: 0,
    chAds: 0,
    credito: 4,
    ementa: "Eletiva ou optativa focada em pesquisa científica em publicidade, com produção de artigo de conclusão sob supervisão de orientação docente.",
    praticaAtividade: "Pesquisa documental, bibliográfica autónoma e ensaios complementares",
    ambientePratica: "Ambiente Virtual de Aprendizagem (AVA)",
    nivelExigencia: "Exigência Média"
  },

  // --- 7º SEMESTRE ---
  {
    id: "16061PP",
    periodo: 7,
    nome: "Comunicação Integrada",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 40,
    chTeo: 40,
    chPra: 0,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 7,
    credito: 2,
    ementa: "Estratégias de relações públicas, assessoria de imprensa, comunicação interna e publicidade atuando sob uma perspectiva unificada para alinhar o discurso e reputação das marcas.",
    praticaAtividade: "Media training simulado e estruturação de plano de gerenciamento de crise",
    ambientePratica: "Sala de Aula",
    nivelExigencia: "Exigência Média"
  },
  {
    id: "16097PP",
    periodo: 7,
    nome: "Marketing de Conteúdo",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 40,
    chTeo: 40,
    chPra: 0,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 7,
    credito: 2,
    ementa: "Conceituação de convergência digital e transmedia. Branded content, inbound marketing, planejamento e redação de conteúdo estratégico para diferentes redes sociais de marca.",
    praticaAtividade: "Planejamento editorial de rede social e redação de posts estratégicos",
    ambientePratica: "Sala de Aula / Laboratório de Informática",
    nivelExigencia: "Exigência Média"
  },
  {
    id: "16098PP",
    periodo: 7,
    nome: "Produção Científica em Publicidade e Propaganda",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 80,
    chTeo: 80,
    chPra: 0,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 13,
    credito: 4,
    ementa: "Metodologia de pesquisa científica aplicada à comunicação de massa, redação de artigo técnico-científico do TCC final, e preparação acadêmica para defesa em banca.",
    praticaAtividade: "Coleta e tabulação de dados e escrita formal de artigo acadêmico (TCC)",
    ambientePratica: "Sala de Aula / Biblioteca",
    nivelExigencia: "Exigência Alta"
  },
  {
    id: "16099PP",
    periodo: 7,
    nome: "Projeto Empreender",
    areaConhecimento: "OBRIGATÓRIA DO CURSO",
    tipo: "PRESENCIAL",
    ch: 80,
    chTeo: 10,
    chPra: 70,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 13,
    credito: 4,
    ementa: "Desenvolvimento do TCC ou Projeto Experimental Prático em formato de startup de comunicação, em parceria com a garagem do SEBRAE para validação de novos negócios.",
    praticaAtividade: "Modelagem de negócios de comunicação, prototipagem e pitch formal",
    ambientePratica: "Agência Experimental (LabCom) / SEBRAE",
    nivelExigencia: "Exigência Alta"
  },
  {
    id: "206ADM",
    periodo: 7,
    nome: "Análise Mercadológica",
    areaConhecimento: "OBRIGATÓRIA - NÚCLEO COMUM",
    tipo: "PRESENCIAL",
    ch: 80,
    chTeo: 80,
    chPra: 0,
    chEst: 0,
    chEad: 0,
    chExt: 0,
    chAds: 13,
    credito: 4,
    ementa: "Segmentação de mercado e posicionamento avançado. Análise de concorrência direta e benchmarking, mensuração de KPIs corporativos e precificação mercadológica.",
    praticaAtividade: "Definição de preço, posicionamento mercadológico e análise de matriz SWOT",
    ambientePratica: "Sala de Aula",
    nivelExigencia: "Exigência Alta"
  }
];
